# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
baseurl: "marapauline.github.io"

# UI configs
title: "analog photography by mara"
subtitle: ""
author:  ""
header:
 title: "analog photography"
 subtitle: "by mara pauline"
footer:
 name: ""
 bio: "experiments in analog photography starting in 2021"
social_urls:
  instagram: "https://www.instagram.com/mara_pauline"
