title: analog photography by mara pauline
author: mara pauline
email: 
description: >-
  experiments in analog photography since 2021

social:
  twitter:
  facebook:
  instagram:
  github:
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
